CREATE TABLE IF NOT EXISTS activity_plans (
  id CHAR(36) PRIMARY KEY,
  organization_id CHAR(36) NOT NULL,
  actor_user_id CHAR(36) NOT NULL,
  agent_run_id CHAR(36) NOT NULL,
  title VARCHAR(160) NOT NULL,
  objective VARCHAR(1000) NOT NULL,
  audience VARCHAR(500) NOT NULL,
  venue VARCHAR(300) NOT NULL DEFAULT '',
  starts_at DATETIME(3) NULL,
  ends_at DATETIME(3) NULL,
  expected_participants INT NOT NULL DEFAULT 0,
  budget VARCHAR(200) NOT NULL DEFAULT '',
  constraints VARCHAR(2000) NOT NULL DEFAULT '',
  context_refs_json TEXT NOT NULL,
  status VARCHAR(24) NOT NULL,
  approved_by CHAR(36) NULL,
  approved_at DATETIME(3) NULL,
  project_id CHAR(36) NULL,
  announcement_content_id CHAR(36) NULL,
  approved_actions_json TEXT NOT NULL,
  created_at DATETIME(3) NOT NULL,
  updated_at DATETIME(3) NOT NULL,
  UNIQUE KEY idx_activity_plans_agent_run_id (agent_run_id),
  KEY idx_activity_plans_organization_id (organization_id),
  KEY idx_activity_plans_actor_user_id (actor_user_id),
  KEY idx_activity_plans_starts_at (starts_at),
  KEY idx_activity_plans_ends_at (ends_at),
  KEY idx_activity_plans_status (status),
  KEY idx_activity_plans_approved_by (approved_by),
  KEY idx_activity_plans_approved_at (approved_at),
  KEY idx_activity_plans_project_id (project_id),
  KEY idx_activity_plans_announcement_content_id (announcement_content_id),
  KEY idx_activity_plans_created_at (created_at)
)
 ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
