CREATE TABLE IF NOT EXISTS integration_configurations (
  id CHAR(36) PRIMARY KEY,
  organization_id CHAR(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  public_web_base_url VARCHAR(500) NOT NULL DEFAULT '',
  email_driver VARCHAR(24) NOT NULL DEFAULT 'disabled',
  smtp_host VARCHAR(255) NOT NULL DEFAULT '',
  smtp_port INT NOT NULL DEFAULT 587,
  smtp_username VARCHAR(255) NOT NULL DEFAULT '',
  smtp_password_encrypted TEXT NOT NULL,
  smtp_from_address VARCHAR(254) NOT NULL DEFAULT '',
  smtp_from_name VARCHAR(160) NOT NULL DEFAULT '',
  smtp_security VARCHAR(24) NOT NULL DEFAULT 'starttls',
  smtp_timeout_seconds INT NOT NULL DEFAULT 8,
  storage_driver VARCHAR(24) NOT NULL DEFAULT 'local',
  s3_endpoint VARCHAR(500) NOT NULL DEFAULT '',
  s3_access_key_encrypted TEXT NOT NULL,
  s3_secret_key_encrypted TEXT NOT NULL,
  s3_bucket VARCHAR(255) NOT NULL DEFAULT '',
  s3_region VARCHAR(120) NOT NULL DEFAULT '',
  s3_use_ssl BOOLEAN NOT NULL DEFAULT TRUE,
  updated_by CHAR(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  created_at DATETIME(3) NOT NULL,
  updated_at DATETIME(3) NOT NULL,
  UNIQUE KEY idx_integration_configurations_organization_id (organization_id),
  KEY idx_integration_configurations_updated_by (updated_by),
  CONSTRAINT fk_integration_configurations_organization FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_integration_configurations_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
